### ISSUE TITLE
Iusse on building

### ISSUE THREAD

**Issue by ghost** [ast261/twrp_device_motorola_miami#2]
Hello, I'm trying to build the recover as your instructions, but I get this errors:

```
myusr@myusr-vmwarevirtualplatform:~$ . build/envsetup.sh; lunch twrp_miami-eng; mka bootimage
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
build/make/core/product_config.mk:160: error: Can not locate config makefile for product "twrp_miami".
13:09:57 dumpvars failed with: exit status 1
/usr/bin/env: ‘python’: No such file or directory
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
build/make/core/product_config.mk:160: error: Can not locate config makefile for product "twrp_miami".
13:09:58 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
build/make/core/product_config.mk:160: error: Can not locate config makefile for product "twrp_miami".
13:09:58 dumpvars failed with: exit status 1

** Don't have a product spec for: 'twrp_miami'
** Do you have the right repo manifest?

13:09:58 ************************************************************
13:09:58 You are building on a machine with 8.88GB of RAM
13:09:58 
13:09:58 The minimum required amount of free memory is around 16GB,
13:09:58 and even with that, some configurations may not work.
13:09:58 
13:09:58 If you run into segfaults or other errors, try reducing your
13:09:58 -j value.
13:09:58 ************************************************************
build/make/core/soong_config.mk:194: warning: BOARD_PLAT_PUBLIC_SEPOLICY_DIR has been depr
ecated. Use SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS instead.
build/make/core/soong_config.mk:195: warning: BOARD_PLAT_PRIVATE_SEPOLICY_DIR has been dep
recated. Use SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS instead.
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=12
TARGET_PRODUCT=aosp_arm
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-6.1.0-15-amd64-x86_64-PeppermintOS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=SP2A.220405.004
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/generic/goldfish device/generic/goldfish-opengl
============================================
[100% 1/1] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
cd "$(dirname "out/soong/.bootstrap/bin/soong_build")" && BUILDER="$PWD/$(basename "out/so
ong/.bootstrap/bin/soong_build")" && cd / && env -i "$BUILDER"     --top "$TOP"     --out 
"out/soong"     -n "out"     -d "out/soong/build.ninja.d"     -t -l out/.module_paths/Andr
oid.bp.list -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja --av
ailable_env out/soong/soong.environment.available --used_env out/soong/soong.environment.u
sed Android.bp
***************************************************************************
Could not find ui.xml for TW_THEME: not set
Set TARGET_SCREEN_WIDTH and TARGET_SCREEN_HEIGHT to automatically select
an appropriate theme, or set TW_THEME to one of the following:
landscape_hdpi landscape_mdpi portrait_hdpi portrait_mdpi watch_mdpi
****************************************************************************
(theme selection failed; exiting)
13:10:01 soong bootstrap failed with: exit status 1

#### failed to build some targets (3 seconds) ####

```

**Comment by ast261** [comment]
```
** Don't have a product spec for: 'twrp_miami'
** Do you have the right repo manifest?
```

Do you have the following file in directory `.repo/local_manifests/local_manifests.xml` with the content from the README ?

**Comment by ghost** [comment]
> ```
> ** Don't have a product spec for: 'twrp_miami'
> ** Do you have the right repo manifest?
> ```
> 
> Do you have the following file in directory `.repo/local_manifests/local_manifests.xml` with the content from the README ?

yes

**Comment by ast261** [comment]
`/usr/bin/env: ‘python’: No such file or directory`

Check your Python installation.

**Comment by ghost** [comment]
> `/usr/bin/env: ‘python’: No such file or directory`
> 
> Check your Python installation.

done, reinstalled it and pyton error is gone, but still get 
build/make/core/product_config.mk:160: error: Can not locate config makefile for product "twrp_miami".

**Comment by ast261** [comment]
Post the content of `.repo/local_manifests/local_manifests.xml`

**Comment by ghost** [comment]
![image](https://github.com/ast261/twrp_device_motorola_miami/assets/82973069/6d7785b7-825f-47f5-94a7-f03fc34f3941)
![image](https://github.com/ast261/twrp_device_motorola_miami/assets/82973069/31934561-8ce1-484c-b8e8-2b49059b81fa)

`✗]─[test@parrot]─[~]
└──╼ $. build/envsetup.sh; lunch twrp_miami-eng; mka bootimage
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
build/make/core/product_config.mk:160: error: Can not locate config makefile for product "twrp_miami".
14:07:22 dumpvars failed with: exit status 1
Device miami not found. Attempting to retrieve device repository from TeamWin Github (http://github.com/TeamWin).
Repository for miami not found in the TeamWin Github repository list.
If this is in error, you may need to manually add it to your .repo/local_manifests/roomservice.xml
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
build/make/core/product_config.mk:160: error: Can not locate config makefile for product "twrp_miami".
14:07:23 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
build/make/core/product_config.mk:160: error: Can not locate config makefile for product "twrp_miami".
14:07:23 dumpvars failed with: exit status 1

** Don't have a product spec for: 'twrp_miami'
** Do you have the right repo manifest?

14:07:24 ************************************************************
14:07:24 You are building on a machine with 6.7GB of RAM
14:07:24 
14:07:24 The minimum required amount of free memory is around 16GB,
14:07:24 and even with that, some configurations may not work.
14:07:24 
14:07:24 If you run into segfaults or other errors, try reducing your
14:07:24 -j value.
14:07:24 ************************************************************
build/make/core/soong_config.mk:194: warning: BOARD_PLAT_PUBLIC_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS instead.
build/make/core/soong_config.mk:195: warning: BOARD_PLAT_PRIVATE_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS instead.
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=12
TARGET_PRODUCT=aosp_arm
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-6.5.0-13parrot1-amd64-x86_64-Parrot-Security-6.0-(lorikeet)
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=SP2A.220405.004
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/generic/goldfish device/generic/goldfish-opengl
============================================
[100% 1/1] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
cd "$(dirname "out/soong/.bootstrap/bin/soong_build")" && BUILDER="$PWD/$(basename "out/soong/.bootstrap/bin/soong_build")" && cd / && env -i "$BUILDER"     --top "$TOP"   
  --out "out/soong"     -n "out"     -d "out/soong/build.ninja.d"     -t -l out/.module_paths/Android.bp.list -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/
build.ninja --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used Android.bp
***************************************************************************
Could not find ui.xml for TW_THEME: not set
Set TARGET_SCREEN_WIDTH and TARGET_SCREEN_HEIGHT to automatically select
an appropriate theme, or set TW_THEME to one of the following:
landscape_hdpi landscape_mdpi portrait_hdpi portrait_mdpi watch_mdpi
****************************************************************************
(theme selection failed; exiting)
14:07:25 soong bootstrap failed with: exit status 1

#### failed to build some targets (2 seconds) ####
`

**Comment by AMT-Cheif** [comment]
✗]─[test@parrot]─[~]
└──╼ $. build/envsetup.sh; lunch twrp_miami-eng; mka bootimage
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
build/make/core/product_config.mk:160: error: Can not locate config makefile for product "twrp_miami".
14:07:22 dumpvars failed with: exit status 1
Device miami not found. Attempting to retrieve device repository from TeamWin Github (http://github.com/TeamWin).
Repository for miami not found in the TeamWin Github repository list.
If this is in error, you may need to manually add it to your .repo/local_manifests/roomservice.xml
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
build/make/core/product_config.mk:160: error: Can not locate config makefile for product "twrp_miami".
14:07:23 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
build/make/core/product_config.mk:160: error: Can not locate config makefile for product "twrp_miami".
14:07:23 dumpvars failed with: exit status 1

** Don't have a product spec for: 'twrp_miami'
** Do you have the right repo manifest?

14:07:24 ************************************************************
14:07:24 You are building on a machine with 6.7GB of RAM
14:07:24 
14:07:24 The minimum required amount of free memory is around 16GB,
14:07:24 and even with that, some configurations may not work.
14:07:24 
14:07:24 If you run into segfaults or other errors, try reducing your
14:07:24 -j value.
14:07:24 ************************************************************
build/make/core/soong_config.mk:194: warning: BOARD_PLAT_PUBLIC_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS instead.
build/make/core/soong_config.mk:195: warning: BOARD_PLAT_PRIVATE_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS instead.
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=12
TARGET_PRODUCT=aosp_arm
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-6.5.0-13parrot1-amd64-x86_64-Parrot-Security-6.0-(lorikeet)
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=SP2A.220405.004
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/generic/goldfish device/generic/goldfish-opengl
============================================
[100% 1/1] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
cd "$(dirname "out/soong/.bootstrap/bin/soong_build")" && BUILDER="$PWD/$(basename "out/soong/.bootstrap/bin/soong_build")" && cd / && env -i "$BUILDER"     --top "$TOP"   
  --out "out/soong"     -n "out"     -d "out/soong/build.ninja.d"     -t -l out/.module_paths/Android.bp.list -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/
build.ninja --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used Android.bp
***************************************************************************
Could not find ui.xml for TW_THEME: not set
Set TARGET_SCREEN_WIDTH and TARGET_SCREEN_HEIGHT to automatically select
an appropriate theme, or set TW_THEME to one of the following:
landscape_hdpi landscape_mdpi portrait_hdpi portrait_mdpi watch_mdpi
****************************************************************************
(theme selection failed; exiting)
14:07:25 soong bootstrap failed with: exit status 1

#### failed to build some targets (2 seconds) ####

**Comment by ast261** [comment]
The manifest is in the wrong folder (`~/.repo`).
You must move the subfolder `local_manifests` to the directory where you checked out the twrp source code.
Folder `.repo` already exists there with subfolders like `manifests`, `manifests.git` etc.

**Comment by ghost** [comment]
I reset my VM and started again: 
-Created a new folder twrptest
-repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
this create under twrptest a folder named .repo with many subfolders manifests, manifests.git  etc.
should I put the local_manifests folder in twrptest? I correctly understood?

**Comment by ast261** [comment]
`should I put the local_manifests folder in twrptest ?`

No. In `.repo`
